use MealPlanner;

insert into recipes (recipeDescription, recipeName, instructions, cookTime, prepTime, recipeType, glutenFree, vegetarianFriendly, dairyFree, nutFree, veganFriendly, servings, caloriesPerServing, fat, carbohydrates, protein, fiber, cholesterol, sodium, recipeImage)
values ('Makes fluffy pancakes with a consistency and taste comparable to those made with wheat flour. Serve with your choice of condiments.', 'Delicious Gluten-Free Pancakes', 'In a bowl, mix or sift together the rice flour, tapioca flour, potato starch, dry buttermilk powder, sugar substitute, baking powder, baking soda, salt, and xanthan gum. Stir in eggs, water, and oil until well blended and few lumps remain. | Heat a large, well-oiled skillet or griddle over medium high heat. Spoon batter onto skillet and cook until bubbles begin to form. Flip, and continue cooking until golden brown on bottom. Serve immediately with condiments of your choice.', 15, 20, 'Breakfast', 1, 1, 0, 1, 0, 10, 147, 5.8, 20.4, 3.1, 0.7, 29, 269, 'https://images.media-allrecipes.com/userphotos/720x405/385145.jpg');

insert into recipes (recipeDescription, recipeName, instructions, cookTime, prepTime, recipeType, glutenFree, vegetarianFriendly, dairyFree, nutFree, veganFriendly, servings, caloriesPerServing, fat, carbohydrates, protein, fiber, cholesterol, sodium, recipeImage)
values ('I made this for my mom''s 65th birthday and frosted it with a simple vanilla buttercream. No one can tell it''s gluten free!', 'Gluten-Free Coconut Cake', 'Preheat oven to 350 degrees F (175 degrees C). Grease and flour a 9x13-inch baking dish. | Whisk flour, sugar, coconut, walnuts, baking powder, baking soda, xanthan gum, and salt together in a bowl. Add coconut milk, vegetable oil, eggs, and vanilla extract; mix until batter is smooth. Spread batter into the prepared baking dish. | Bake in the preheated oven until a toothpick inserted in the center comes out clean, about 45 minutes.', 45, 15, 'Dessert', 1, 1, 0, 0, 0, 16, 345, 22.3, 35.2, 4.3, 2.9, 46, 355, 'https://images.media-allrecipes.com/userphotos/720x405/2184389.jpg');

insert into recipes (recipeDescription, recipeName, instructions, cookTime, prepTime, recipeType, glutenFree, vegetarianFriendly, dairyFree, nutFree, veganFriendly, servings, caloriesPerServing, fat, carbohydrates, protein, fiber, cholesterol, sodium, recipeImage)
values ('For people that are gluten-intolerant, low-carb, paleo, or whatever, it can be hard to go without pizza. This dish makes it a lot easier. It is made pretty much exactly the same as pizza, but with ground beef as the crust. Sounds weird at first, but it is absolutely delicious and very filling. This is something great to make ahead of time and then eat as leftovers later on. It''s great hot or cold, just like pizza! I find that if you make 6 square slices, each slice is usually more than enough to fill you up. Feel free to add whatever toppings you normally eat on pizza. It will taste just as good!', 'Pepperoni Meatza', 'Preheat oven to 450 degrees F (230 degrees C). | Mix together salt, caraway seeds, oregano, garlic salt, ground black pepper, and crushed red pepper flakes in a small bowl. | Mix ground beef and eggs in a mixing bowl until thoroughly incorporated. Add Parmesan cheese and seasoning mixture to beef; combine. Press ground beef mixture into a 12x17-inch pan, spread out evenly. | Bake in the preheated oven until meat is no longer pink, about 10 minutes. Drain grease. | Set oven rack about 6 inches from the heat source and turn on the oven''s broiler. | Sprinkle 1/3 of the mozzarella cheese over baked meat, followed by tomato sauce in an even layer. Sprinkle another 1/3 of the mozzarella cheese over the sauce and top with slices of pepperoni. Sprinkle remaining mozzarella cheese over pizza. | Broil until cheese is melted, bubbling, and lightly browned, 3 to 5 minutes.', 15, 30, 'Lunch', 1, 0, 0, 1, 0, 6, 506, 27.8, 5.1, 56.5, 1, 220, 2521, 'https://images.media-allrecipes.com/userphotos/720x405/2083257.jpg');