use MealPlanner;

insert into recipes (recipeDescription, recipeName, instructions, cookTime, prepTime, recipeType, glutenFree, vegetarianFriendly, dairyFree, nutFree, veganFriendly, servings, caloriesPerServing, fat, carbohydrates, protein, fiber, cholesterol, sodium, recipeImage)
values ('Makes fluffy pancakes with a consistency and taste comparable to those made with wheat flour. Serve with your choice of condiments.', 'Delicious Gluten-Free Pancakes', 'In a bowl, mix or sift together the rice flour, tapioca flour, potato starch, dry buttermilk powder, sugar substitute, baking powder, baking soda, salt, and xanthan gum. Stir in eggs, water, and oil until well blended and few lumps remain. | Heat a large, well-oiled skillet or griddle over medium high heat. Spoon batter onto skillet and cook until bubbles begin to form. Flip, and continue cooking until golden brown on bottom. Serve immediately with condiments of your choice.', 15, 20, 'Breakfast', 1, 1, 0, 1, 0, 10, 147, 5.8, 20.4, 3.1, 0.7, 29, 269, 'https://images.media-allrecipes.com/userphotos/720x405/385145.jpg');

insert into recipes (recipeDescription, recipeName, instructions, cookTime, prepTime, recipeType, glutenFree, vegetarianFriendly, dairyFree, nutFree, veganFriendly, servings, caloriesPerServing, fat, carbohydrates, protein, fiber, cholesterol, sodium, recipeImage)
values ('I made this for my mom''s 65th birthday and frosted it with a simple vanilla buttercream. No one can tell it''s gluten free!', 'Gluten-Free Coconut Cake', 'Preheat oven to 350 degrees F (175 degrees C). Grease and flour a 9x13-inch baking dish. | Whisk flour, sugar, coconut, walnuts, baking powder, baking soda, xanthan gum, and salt together in a bowl. Add coconut milk, vegetable oil, eggs, and vanilla extract; mix until batter is smooth. Spread batter into the prepared baking dish. | Bake in the preheated oven until a toothpick inserted in the center comes out clean, about 45 minutes.', 45, 15, 'Dessert', 1, 1, 0, 0, 0, 16, 345, 22.3, 35.2, 4.3, 2.9, 46, 355, 'https://images.media-allrecipes.com/userphotos/720x405/2184389.jpg');

insert into recipes (recipeDescription, recipeName, instructions, cookTime, prepTime, recipeType, glutenFree, vegetarianFriendly, dairyFree, nutFree, veganFriendly, servings, caloriesPerServing, fat, carbohydrates, protein, fiber, cholesterol, sodium, recipeImage)
values ('For people that are gluten-intolerant, low-carb, paleo, or whatever, it can be hard to go without pizza. This dish makes it a lot easier. It is made pretty much exactly the same as pizza, but with ground beef as the crust. Sounds weird at first, but it is absolutely delicious and very filling. This is something great to make ahead of time and then eat as leftovers later on. It''s great hot or cold, just like pizza! I find that if you make 6 square slices, each slice is usually more than enough to fill you up. Feel free to add whatever toppings you normally eat on pizza. It will taste just as good!', 'Pepperoni Meatza', 'Preheat oven to 450 degrees F (230 degrees C). | Mix together salt, caraway seeds, oregano, garlic salt, ground black pepper, and crushed red pepper flakes in a small bowl. | Mix ground beef and eggs in a mixing bowl until thoroughly incorporated. Add Parmesan cheese and seasoning mixture to beef; combine. Press ground beef mixture into a 12x17-inch pan, spread out evenly. | Bake in the preheated oven until meat is no longer pink, about 10 minutes. Drain grease. | Set oven rack about 6 inches from the heat source and turn on the oven''s broiler. | Sprinkle 1/3 of the mozzarella cheese over baked meat, followed by tomato sauce in an even layer. Sprinkle another 1/3 of the mozzarella cheese over the sauce and top with slices of pepperoni. Sprinkle remaining mozzarella cheese over pizza. | Broil until cheese is melted, bubbling, and lightly browned, 3 to 5 minutes.', 15, 30, 'Lunch', 1, 0, 0, 1, 0, 6, 506, 27.8, 5.1, 56.5, 1, 220, 2521, 'https://images.media-allrecipes.com/userphotos/720x405/2083257.jpg');

insert into recipes (recipeDescription, recipeName, instructions, cookTime, prepTime, recipeType, glutenFree, vegetarianFriendly, dairyFree, nutFree, veganFriendly, servings, caloriesPerServing, fat, carbohydrates, protein, fiber, cholesterol, sodium, recipeImage)
values ('It takes a little work, but it is worth it.', 'World''s Best Lasagna', 'In a Dutch oven, cook sausage, ground beef, onion, and garlic over medium heat until well browned. Stir in crushed tomatoes, tomato paste, tomato sauce, and water. Season with sugar, basil, fennel seeds, Italian seasoning, 1 tablespoon salt, pepper, and 2 tablespoons parsley. Simmer, covered, for about 1 1/2 hours, stirring occasionally. | Bring a large pot of lightly salted water to a boil. Cook lasagna noodles in boiling water for 8 to 10 minutes. Drain noodles, and rinse with cold water. In a mixing bowl, combine ricotta cheese with egg, remaining parsley, and 1/2 teaspoon salt. | Preheat oven to 375 degrees F (190 degrees C). | To assemble, spread 1 1/2 cups of meat sauce in the bottom of a 9x13 inch baking dish. Arrange 6 noodles lengthwise over meat sauce. Spread with one half of the ricotta cheese mixture. Top with a third of mozzarella cheese slices. Spoon 1 1/2 cups meat sauce over mozzarella, and sprinkle with 1/4 cup Parmesan cheese. Repeat layers, and top with remaining mozzarella and Parmesan cheese. Cover with foil: to prevent sticking, either spray foil with cooking spray, or make sure the foil does not touch the cheese. | Bake in preheated oven for 25 minutes. Remove foil, and bake an additional 25 minutes. Cool for 15 minutes before serving.', 150, 30, 'Dinner', 0, 0, 0, 1, 0, 12, 448, 21.3, 36.5, 29.7, 4, 82, 1788, 'https://images.media-allrecipes.com/userphotos/720x405/3359675.jpg');

insert into recipes (recipeDescription, recipeName, instructions, cookTime, prepTime, recipeType, glutenFree, vegetarianFriendly, dairyFree, nutFree, veganFriendly, servings, caloriesPerServing, fat, carbohydrates, protein, fiber, cholesterol, sodium, recipeImage)
values ('No two spaghetti aglio e olio recipes are alike, but this one is pretty true to the classic method. The key is slowly toasting the garlic slices to a perfect golden-brown in the olive oil. If it''s too light, you don''t get the full flavor and if it''s too dark it gets bitter. My advice? Do it perfectly.', 'Spaghetti Aglio e Olio', 'Bring a large pot of lightly salted water to a boil. Cook spaghetti in the boiling water, stirring occasionally until cooked through but firm to the bite, about 12 minutes. Drain and transfer to a pasta bowl. | Combine garlic and olive oil in a cold skillet. Cook over medium heat to slowly toast garlic, about 10 minutes. Reduce heat to medium-low when olive oil begins to bubble. Cook and stir until garlic is golden brown, about another 5 minutes. Remove from heat. | Stir red pepper flakes, black pepper, and salt into the pasta. Pour in olive oil and garlic, and sprinkle on Italian parsley and half of the Parmigiano-Reggiano cheese; stir until combined. | Serve pasta topped with the remaining Parmigiano-Reggiano cheese.', 22, 10, 'Dinner', 0, 1, 1, 1, 1, 2, 1509, 69, 174.8, 45.8, 7.8, 35, 710, 'https://images.media-allrecipes.com/userphotos/720x405/3727226.jpg');

insert into recipes (recipeDescription, recipeName, instructions, cookTime, prepTime, recipeType, glutenFree, vegetarianFriendly, dairyFree, nutFree, veganFriendly, servings, caloriesPerServing, fat, carbohydrates, protein, fiber, cholesterol, sodium, recipeImage)
values ('I modified an old family favorite recipe upon going gluten-free. It is easy and super yummy and naughty. If you prefer to use a premade GF flour mix instead of the flours suggested, it will work just as well.', 'The Best Gluten Free Brownies Ever...Seriously', 'Preheat oven to 350 degrees F (175 degrees C). Grease a 9x9-inch baking pan. | Toss walnuts and chocolate chips with 1 teaspoon cocoa powder in a bowl until well coated; set aside. Mix tapioca flour, sorghum flour, teff flour, 1/3 cup cocoa powder, xanthan gum, and salt together in a separate bowl. | Beat butter and sugar together in a separate large bowl until creamy. Stir in eggs and vanilla extract. Gradually add flour mixture to butter mixture until fully incorporated. Fold in nuts and chocolate chips. Spread batter into the prepared baking pan. | Bake in the preheated oven until the top is dry and the edges have started to pull away from the sides of the pan, about 25 minutes.', 25, 20, 'Dessert', 1, 1, 0, 0, 0, 9, 375, 21.8, 45.9, 4.8, 4.1, 68, 105, 'https://images.media-allrecipes.com/userphotos/720x405/3564251.jpg');